baseURL: http://localhost:80
projectName: GreenWave
scenarios:
  - name: Consulter la page d'acceuil
    path: ./scenarios/consult_mainPage.js
  - name: Consulter une musique
    path: ./scenarios/consult_music.js
  - name: Rechercher une musique
    path: ./scenarios/consult_search_music.js
  - name: Ajouter une musique au favori 
    path: ./scenarios/add_music_favorite.js
containers:
  - greenwave-static_hosting-1
  - greenwave-backend-1